#!/bin/bash -e
set -u

# Compare response
# ./compareFlavourCorrectionGraphs.py \
# --input 80X_QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_useFitRange_absEta_hadronParton_wideBinning.root --label "PYTHIA8" \
# --input 80X_QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_useFitRange_absEta_hadronParton_wideBinning.root --label "HERWIG++" \
# --outputDir 80X_QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/comparePythiaHerwigFitMin20 \
# --title "With L1 (Summer16_07Aug2017_V11_L1fix)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_useFitRange_absEta_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_useFitRange_absEta_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/comparePythiaHerwigFitMin15FitFuncStandard \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input 80X_QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_fitFuncpowerlaw_useFitRange_absEta_hadronParton_wideBinning.root --label "PYTHIA8" \
# --input 80X_QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_fitFuncpowerlaw_useFitRange_absEta_hadronParton_wideBinning.root --label "HERWIG++" \
# --outputDir 80X_QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V11_L1fix_HadronParton_nbinsrelrsp_10k/comparePythiaHerwigFitMin20_fitFuncpowerlaw \
# --title "With L1 (Summer16_07Aug2017_V11_L1fix)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_absEta_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_absEta_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k/comparePythiaHerwigFitMin15FitFuncPowerlaw \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_useFitRange_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_useFitRange_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandard \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandard/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncPowerlaw \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncPowerlaw/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_useFitRange_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_useFitRange_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_useFitRange_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_useFitRange_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_hadronParton_useLastFitParams.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_hadronParton_useLastFitParams.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard_useLastFitParams2 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandard_useLastFitParams/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncpowerlaw_useFitRange_hadronParton.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncPowerlaw \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncPowerlaw/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20

# ./compareFlavourResponseHists.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/jra_QCD_Pt_15toInf_NoJEC_newFlav_ak4pfchs_L1FastJet_rspRangeLarge_hadronParton.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/jra_QCD_Pt_15to7000_Herwig_NoJEC_newFlav_ak4pfchs_L1FastJet_rspRangeLarge_hadronParton_responseOnly.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigRspHists \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigRspHists \
# --title "With L1 (Summer16_07Aug2017_V15)" --sampleName "QCD MC"

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_useLastFitParam_minRelCorErr0p001.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_useLastFitParam_minRelCorErr0p001.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardUseLastFitParamsMinRelCorErr0p001 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardUseLastFitParamsMinRelCorErr0p001/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_useLastFitParam_minRelCorErr0p01.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_useLastFitParam_minRelCorErr0p01.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardUseLastFitParamsMinRelCorErr0p01 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardUseLastFitParamsMinRelCorErr0p01/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p01.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin20_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p01.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin20FitFuncStandardUseLastFitParamsMinRelCorErr0p01 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin20FitFuncStandardUseLastFitParamsMinRelCorErr0p01/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p01.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p01.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardUseLastFitParamsMinRelCorErr0p01 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardUseLastFitParamsMinRelCorErr0p01/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p005.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_useLastFitParams_minRelCorErr0p005.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardUseLastFitParamsMinRelCorErr0p005 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardUseLastFitParamsMinRelCorErr0p005/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_minRelCorErr0p005.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin15_fitFuncstandard_HadronParton_minRelCorErr0p005.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardMinRelCorErr0p005 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin15FitFuncStandardMinRelCorErr0p005/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnover \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnover/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOne \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOne/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncpowerlaw_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncpowerlaw_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncPowerlawMinRelCorErr0p005SetFitMinTurnoverPlusOne \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncPowerlawMinRelCorErr0p005SetFitMinTurnoverPlusOne/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0SetFitMinTurnoverPlateauBelowRangeMin \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0SetFitMinTurnoverPlateauBelowRangeMin/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "No min. rel. err" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "0.5% min. rel. err" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareFitMin10FitFuncStandardMinRelCorErr0vs0p005SetFitMinTurnoverPlateauBelowRangeMin \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareFitMin10FitFuncStandardMinRelCorErr0vs0p005SetFitMinTurnoverPlateauBelowRangeMin/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "No min. rel. err" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "0.5% min. rel. err" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareFitMin10FitFuncStandardMinRelCorErr0vs0p005SetFitMinTurnoverPlateauBelowRangeMin \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareFitMin10FitFuncStandardMinRelCorErr0vs0p005SetFitMinTurnoverPlateauBelowRangeMin/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 20 --chi2

# Using auto-decide by chi2 between 0 min rel corr err, and some non-0 value
# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "0.5% min rel error, chi2 compete" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "0.5% min rel error, chi2 compete" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "1% min rel error, chi2 compete" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_expandP3Lim_minRelCorErrChi2Compete.root --label "1% min rel error, chi2 compete" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMinExpandP3Lim_minRelCorErrChi2Compete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --ylim 0.9 1.65 --vertLine 15 --chi2

# Using auto-decide by maximum relative diff between func & graph, to decide between 0 min rel corr err or non-0
# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "0.5% min rel error, max rel diff compete" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "0.5% min rel error, max rel diff compete" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2
# # --ylim 0.9 1.65 \

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "1% min rel error, max rel diff compete" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnover_plateauBelowRangeMin.root --label "Normal, no min rel error" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "1% min rel error, max rel diff compete" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p05_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p05_setFitMinTurnover_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p05SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p05SetFitMinTurnoverPlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)"  --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrChi2Compete.root --label "Choose by chi2" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrChi2Compete.root --label "Choose by chi2" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p005_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2 \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p005SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "PYTHIA8" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "HERWIG++" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2 --ylim 0.9 1.65

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrChi2Compete.root --label "Choose by chi2" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2 \
# --slides QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnoverPlusOne_plateauBelowRangeMin.root --label "Standard fit" \
# --input QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
# --outputDir QCD_Pt_Herwig_NoJEC_relPtHatCut2p5_jtptmin4_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/compareHerwigFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2

./compareFlavourCorrectionGraphs.py \
--input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0_setFitMinTurnoverPlusOne_plateauBelowRangeMin.root --label "Standard fit" \
--input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
--outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompete_vs_without \
--title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2


# ./compareFlavourCorrectionGraphs.py \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrChi2Compete.root --label "Choose by chi2" \
# --input QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/l2_standardMedianErr_allMedian_rspRangeLarge_fitMin10_fitFuncstandard_HadronParton_minRelCorErr0p01_setFitMinTurnoverPlusOne_plateauBelowRangeMin_minRelCorErrMaxRelDiffCompete.root --label "Choose by max rel diff" \
# --outputDir QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2 \
# --slides QCD_Pt_NoJEC_relPtHatCut2p5_jtptmin4_withPF_PhysicsAlgoHadron_L1FastJet_Summer16_07Aug2017_V15_HadronParton_nbinsrelrsp_10k_fineBinning_etaPlusMinus/comparePythiaFitMin10FitFuncStandardMinRelCorErr0p01SetFitMinTurnoverPlusOnePlateauBelowRangeMin_minRelCorErrMaxRelDiffCompeteVsChi2/slides.json \
# --title "With L1 (Summer16_07Aug2017_V15)" --vertLine 15 --chi2
